# Generated by Django 3.2 on 2021-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('filedata', models.FileField(upload_to='')),
                ('visibility', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='userpost',
        ),
    ]
