# Generated by Django 3.2 on 2021-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_auto_20210428_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='userconnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('userConnectionId', models.CharField(max_length=200)),
            ],
        ),
    ]
