# Generated by Django 3.2 on 2021-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_userconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='followcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followId', models.CharField(max_length=200)),
                ('noOfFollow', models.IntegerField(max_length=200)),
            ],
        ),
    ]
